environment: production
chdir: /home/syd/Emojiblog
address: 127.0.0.1
user: root
group: root
port: 3030
pid: /home/syd/Emojiblog/tmp/thin.pid
rackup: /home/syd/Emojiblog/config.ru
log: /home/syd/Emojiblog/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true